#![warn(clippy::pedantic)]
pub fn clean_stop_words(linked_text: &mut String) -> String {
    for stop_word in STOP_WORDS {
        let fully_linked_stop = format!("[[{stop_word}]]");
        let initial_linked_stop = format!("[[{stop_word} ");
        let initial_replacement = format!("{stop_word} [[");
        let final_linked_stop = format!(" {stop_word}]]");
        let final_replacement = format!("]] {stop_word}");
        let full_text = linked_text.replace(&fully_linked_stop, stop_word);
        let initial_text = full_text.replace(&initial_linked_stop, &initial_replacement);
        let cleaned_text = initial_text.replace(&final_linked_stop, &final_replacement);
        *linked_text = cleaned_text
    }
    linked_text.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn clean_fully_linked_stop() {
        let mut input = String::from("[[Able]]");
        let cleaned_input = clean_stop_words(&mut input);
        assert_eq!("Able", cleaned_input);
    }

    #[test]
    fn clean_initially_linked_stop() {
        let mut input = String::from("[[Able ");
        let cleaned_input = clean_stop_words(&mut input);
        assert_eq!("Able [[", cleaned_input);
    }
    
    #[test]
    fn clean_finally_linked_stop() {
        let mut input = String::from(" Able]]");
        let cleaned_input = clean_stop_words(&mut input);
        assert_eq!("]] Able", cleaned_input);
    }
}

static STOP_WORDS: [&str; 2369] = [
    "of", "the", "from",
    "Family", "Families",
    "Able", "About", "Above", "Abst", "Accordance", "According", "Accordingly", "Across", "Act",
    "Actually", "Ad", "Added", "Adj", "Affected", "Affecting", "Affects", "After", "Afterwards",
    "Again", "Against", "Ah", "Ain", "Ain't", "All", "Allow", "Allows", "Almost", "Alone", "Along",
    "Already", "Also", "Although", "Always", "Am", "Among", "Amongst", "Amoungst", "Amount", "An",
    "And", "Announce", "Another", "Any", "Anybody", "Anyhow", "Anymore", "Anyone", "Anything",
    "Anyway", "Anyways", "Anywhere", "Apart", "Apparently", "Appear", "Appreciate", "Appropriate",
    "Approximately", "Are", "Aren", "Arent", "Aren't", "Arise", "Around", "As", "Aside", "Ask",
    "Asking", "Associated", "At", "Auth", "Available", "Away", "Awfully", "Back", "Be", "Became",
    "Because", "Become", "Becomes", "Becoming", "Been", "Before", "Beforehand", "Begin",
    "Beginning", "Beginnings", "Begins", "Behind", "Being", "Believe", "Below", "Beside", "Besides",
    "Best", "Better", "Between", "Beyond", "Bill", "Both", "Bottom", "Brief", "Briefly", "But",
    "Call", "Came", "Can", "Cannot", "Cant", "Can't", "Cause", "Causes", "Certain", "Certainly",
    "Changes", "Clearly", "C'mon", "Come", "Comes", "Concerning", "Consequently", "Consider",
    "Considering", "Contain", "Containing", "Contains", "Corresponding", "Could", "Couldn",
    "Couldnt", "Couldn't", "Course", "Cry", "Currently", "Date", "Definitely", "Describe",
    "Described", "Despite", "Detail", "Did", "Didn", "Didn't", "Different", "Do", "Does", "Doesn",
    "Doesn't", "Doing", "Don", "Done", "Don't", "Down", "Downwards", "Due", "During", "Each",
    "Effect", "Eight", "Eighty", "Either", "Eleven", "Else", "Elsewhere", "Empty", "End", "Ending",
    "Enough", "Entirely", "Especially", "Et-al", "Etc", "Even", "Ever", "Every", "Everybody",
    "Everyone", "Everything", "Everywhere", "Ex", "Exactly", "Example", "Except", "Far", "Few",
    "Fifteen", "Fifth", "Fify", "Fill", "Find", "Fire", "First", "Five", "Fix", "Followed",
    "Following", "Follows", "For", "Former", "Formerly", "Forth", "Forty", "Found", "Four", "From",
    "Front", "Full", "Further", "Furthermore", "Gave", "Get", "Gets", "Getting", "Give", "Given",
    "Gives", "Giving", "Go", "Goes", "Going", "Gone", "Got", "Gotten", "Greetings", "Had", "Hadn",
    "Hadn't", "Happens", "Hardly", "Has", "Hasn", "Hasnt", "Hasn't", "Have", "Haven", "Haven't",
    "Having", "He", "Hed", "He'd", "He'll", "Hello", "Help", "Hence", "Her", "Here", "Hereafter",
    "Hereby", "Herein", "Heres", "Here's", "Hereupon", "Hers", "Herself", "Hes", "He's", "Hi",
    "Hid", "Him", "Himself", "His", "Hither", "Home", "Hopefully", "How", "Howbeit", "However",
    "How's", "Http", "Hundred", "Ibid", "Id", "I'd", "If", "Ignored", "I'll", "I'm", "Immediate",
    "Immediately", "Importance", "Important", "Inasmuch", "Inc", "Indeed", "Index", "Indicate",
    "Indicated", "Indicates", "Information", "Inner", "Insofar", "Instead", "Interest", "Into",
    "Invention", "Inward", "Is", "Isn", "Isn't", "It", "Itd", "It'd", "It'll", "Its", "It's",
    "Itself", "I've", "Just", "Keep", "Keeps", "Kept", "Know", "Known", "Knows", "Largely", "Last",
    "Lately", "Later", "Latter", "Latterly", "Least", "Les", "Less", "Lest", "Let", "Lets", "Let's",
    "Like", "Liked", "Likely", "Line", "Little", "Look", "Looking", "Looks", "Ltd", "Made",
    "Mainly", "Make", "Makes", "Many", "May", "Maybe", "Me", "Mean", "Means", "Meantime",
    "Meanwhile", "Merely", "Might", "Mightn", "Mightn't", "Mill", "Million", "Mine", "Miss", "More",
    "Moreover", "Most", "Mostly", "Move", "Mr", "Mrs", "Ms", "Mt", "Much", "Mug", "Must", "Mustn",
    "Mustn't", "My", "Myself", "Name", "Namely", "Nay", "Near", "Nearly", "Necessarily",
    "Necessary", "Need", "Needn", "Needn't", "Needs", "Neither", "Never", "Nevertheless", "New",
    "Next", "Nine", "Ninety", "No", "Nobody", "Non", "None", "Nonetheless", "Noone", "Nor",
    "Normally", "Nos", "Not", "Noted", "Nothing", "Novel", "Now", "Nowhere", "Obtain", "Obtained",
    "Obviously", "Of", "Off", "Often", "Oh", "Ok", "Okay", "Old", "Om", "Omitted", "On", "Once",
    "One", "Ones", "Only", "Onto", "Or", "Ord", "Other", "Others", "Otherwise", "Ought", "Our",
    "Ours", "Ourselves", "Out", "Outside", "Over", "Overall", "Ow", "Owing", "Own", "Page",
    "Pagecount", "Pages", "Part", "Particular", "Particularly", "Past", "Per", "Perhaps", "Placed",
    "Please", "Plus", "Poorly", "Possible", "Possibly", "Potentially", "Predominantly", "Present",
    "Presumably", "Previously", "Primarily", "Probably", "Promptly", "Proud", "Provides", "Put",
    "Que", "Quickly", "Quite", "Ran", "Rather", "Readily", "Really", "Reasonably", "Recent",
    "Recently", "Ref", "Refs", "Regarding", "Regardless", "Regards", "Related", "Relatively",
    "Research", "Research-articl", "Respectively", "Resulted", "Resulting", "Results", "Right",
    "Run", "Said", "Same", "Saw", "Say", "Saying", "Says", "Sec", "Second", "Secondly", "Section",
    "See", "Seeing", "Seem", "Seemed", "Seeming", "Seems", "Seen", "Self", "Selves", "Sensible",
    "Sent", "Serious", "Seriously", "Seven", "Several", "Shall", "Shan", "Shan't", "She", "Shed",
    "She'd", "She'll", "Shes", "She's", "Should", "Shouldn", "Shouldn't", "Should've", "Show",
    "Showed", "Shown", "Showns", "Shows", "Side", "Significant", "Significantly", "Similar",
    "Similarly", "Since", "Sincere", "Six", "Sixty", "Slightly", "So", "Some", "Somebody",
    "Somehow", "Someone", "Somethan", "Something", "Sometime", "Sometimes", "Somewhat", "Somewhere",
    "Soon", "Sorry", "Specifically", "Specified", "Specify", "Specifying", "Still", "Stop",
    "Strongly", "Sub", "Substantially", "Successfully", "Such", "Sufficiently", "Suggest", "Sup",
    "Sure", "System", "Take", "Taken", "Taking", "Tell", "Ten", "Tends", "Than", "Thank", "Thanks",
    "Thanx", "That", "That'll", "Thats", "That's", "That've", "The", "Their", "Theirs", "Them",
    "Themselves", "Then", "Thence", "There", "Thereafter", "Thereby", "Thered", "Therefore",
    "Therein", "There'll", "Thereof", "Therere", "Theres", "There's", "Thereto", "Thereupon",
    "There've", "These", "They", "Theyd", "They'd", "They'll", "Theyre", "They're", "They've",
    "Thickv", "Thin", "Think", "Third", "This", "Thorough", "Thoroughly", "Those", "Thou", "Though",
    "Thoughh", "Thousand", "Three", "Throug", "Through", "Throughout", "Thru", "Thus", "Til", "To",
    "Together", "Too", "Took", "Top", "Toward", "Towards", "Tried", "Tries", "Truly", "Try",
    "Trying", "Twelve", "Twenty", "Twice", "Two", "U201d", "Um", "Under", "Unfortunately", "Unless",
    "Unlike", "Unlikely", "Until", "Unto", "Up", "Upon", "Ups", "Ur", "Us", "Use", "Used", "Useful",
    "Usefully", "Usefulness", "Uses", "Using", "Usually", "Value", "Various", "Very", "Via", "Viz",
    "Vol", "Vols", "Volumtype", "Want", "Wants", "Was", "Wasn", "Wasnt", "Wasn't", "Way", "We",
    "Wed", "We'd", "Welcome", "Well", "We'll", "Well-b", "Went", "Were", "We're", "Weren", "Werent",
    "Weren't", "We've", "What", "Whatever", "What'll", "Whats", "What's", "When", "Whence",
    "Whenever", "When's", "Where", "Whereafter", "Whereas", "Whereby", "Wherein", "Wheres",
    "Where's", "Whereupon", "Wherever", "Whether", "Which", "While", "Whim", "Whither", "Who",
    "Whod", "Whoever", "Whole", "Who'll", "Whom", "Whomever", "Whos", "Who's", "Whose", "Why",
    "Why's", "Widely", "Will", "Willing", "Wish", "With", "Within", "Without", "Won", "Wonder",
    "Wont", "Won't", "Words", "World", "Would", "Wouldn", "Wouldnt", "Wouldn't", "Yes", "Yet",
    "You", "Youd", "You'd", "You'll", "Your", "Youre", "You're", "Yours", "Yourself", "Yourselves",
    "You've", "Zero", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",
    "January", "February", "March", "April", "May", "June", "July", "August", "September",
    "October", "November", "December", "A", "I", "Able,", "About,", "Above,", "Abst,",
    "Accordance,", "According,", "Accordingly,", "Across,", "Act,", "Actually,", "Ad,", "Added,",
    "Adj,", "Affected,", "Affecting,", "Affects,", "After,", "Afterwards,", "Again,", "Against,",
    "Ah,", "Ain,", "Ain't,", "All,", "Allow,", "Allows,", "Almost,", "Alone,", "Along,", "Already,",
    "Also,", "Although,", "Always,", "Am,", "Among,", "Amongst,", "Amoungst,", "Amount,", "An,",
    "And,", "Announce,", "Another,", "Any,", "Anybody,", "Anyhow,", "Anymore,", "Anyone,",
    "Anything,", "Anyway,", "Anyways,", "Anywhere,", "Apart,", "Apparently,", "Appear,",
    "Appreciate,", "Appropriate,", "Approximately,", "Are,", "Aren,", "Arent,", "Aren't,", "Arise,",
    "Around,", "As,", "Aside,", "Ask,", "Asking,", "Associated,", "At,", "Auth,", "Available,",
    "Away,", "Awfully,", "Back,", "Be,", "Became,", "Because,", "Become,", "Becomes,", "Becoming,",
    "Been,", "Before,", "Beforehand,", "Begin,", "Beginning,", "Beginnings,", "Begins,", "Behind,",
    "Being,", "Believe,", "Below,", "Beside,", "Besides,", "Best,", "Better,", "Between,",
    "Beyond,", "Bill,", "Both,", "Bottom,", "Brief,", "Briefly,", "But,", "Call,", "Came,", "Can,",
    "Cannot,", "Cant,", "Can't,", "Cause,", "Causes,", "Certain,", "Certainly,", "Changes,",
    "Clearly,", "C'mon,", "Come,", "Comes,", "Concerning,", "Consequently,", "Consider,",
    "Considering,", "Contain,", "Containing,", "Contains,", "Corresponding,", "Could,", "Couldn,",
    "Couldnt,", "Couldn't,", "Course,", "Cry,", "Currently,", "Date,", "Definitely,", "Describe,",
    "Described,", "Despite,", "Detail,", "Did,", "Didn,", "Didn't,", "Different,", "Do,", "Does,",
    "Doesn,", "Doesn't,", "Doing,", "Don,", "Done,", "Don't,", "Down,", "Downwards,", "Due,",
    "During,", "Each,", "Effect,", "Eight,", "Eighty,", "Either,", "Eleven,", "Else,", "Elsewhere,",
    "Empty,", "End,", "Ending,", "Enough,", "Entirely,", "Especially,", "Et-al,", "Etc,", "Even,",
    "Ever,", "Every,", "Everybody,", "Everyone,", "Everything,", "Everywhere,", "Ex,", "Exactly,",
    "Example,", "Except,", "Far,", "Few,", "Fifteen,", "Fifth,", "Fify,", "Fill,", "Find,", "Fire,",
    "First,", "Five,", "Fix,", "Followed,", "Following,", "Follows,", "For,", "Former,",
    "Formerly,", "Forth,", "Forty,", "Found,", "Four,", "From,", "Front,", "Full,", "Further,",
    "Furthermore,", "Gave,", "Get,", "Gets,", "Getting,", "Give,", "Given,", "Gives,", "Giving,",
    "Go,", "Goes,", "Going,", "Gone,", "Got,", "Gotten,", "Greetings,", "Had,", "Hadn,", "Hadn't,",
    "Happens,", "Hardly,", "Has,", "Hasn,", "Hasnt,", "Hasn't,", "Have,", "Haven,", "Haven't,",
    "Having,", "He,", "Hed,", "He'd,", "He'll,", "Hello,", "Help,", "Hence,", "Her,", "Here,",
    "Hereafter,", "Hereby,", "Herein,", "Heres,", "Here's,", "Hereupon,", "Hers,", "Herself,",
    "Hes,", "He's,", "Hi,", "Hid,", "Him,", "Himself,", "His,", "Hither,", "Home,", "Hopefully,",
    "How,", "Howbeit,", "However,", "How's,", "Http,", "Hundred,", "Ibid,", "Id,", "I'd,", "If,",
    "Ignored,", "I'll,", "I'm,", "Immediate,", "Immediately,", "Importance,", "Important,",
    "Inasmuch,", "Inc,", "Indeed,", "Index,", "Indicate,", "Indicated,", "Indicates,",
    "Information,", "Inner,", "Insofar,", "Instead,", "Interest,", "Into,", "Invention,", "Inward,",
    "Is,", "Isn,", "Isn't,", "It,", "Itd,", "It'd,", "It'll,", "Its,", "It's,", "Itself,", "I've,",
    "Just,", "Keep,", "Keeps,", "Kept,", "Know,", "Known,", "Knows,", "Largely,", "Last,",
    "Lately,", "Later,", "Latter,", "Latterly,", "Least,", "Les,", "Less,", "Lest,", "Let,",
    "Lets,", "Let's,", "Like,", "Liked,", "Likely,", "Line,", "Little,", "Look,", "Looking,",
    "Looks,", "Ltd,", "Made,", "Mainly,", "Make,", "Makes,", "Many,", "May,", "Maybe,", "Me,",
    "Mean,", "Means,", "Meantime,", "Meanwhile,", "Merely,", "Might,", "Mightn,", "Mightn't,",
    "Mill,", "Million,", "Mine,", "Miss,", "More,", "Moreover,", "Most,", "Mostly,", "Move,", "Mr,",
    "Mrs,", "Ms,", "Mt,", "Much,", "Mug,", "Must,", "Mustn,", "Mustn't,", "My,", "Myself,", "Name,",
    "Namely,", "Nay,", "Near,", "Nearly,", "Necessarily,", "Necessary,", "Need,", "Needn,",
    "Needn't,", "Needs,", "Neither,", "Never,", "Nevertheless,", "New,", "Next,", "Nine,",
    "Ninety,", "No,", "Nobody,", "Non,", "None,", "Nonetheless,", "Noone,", "Nor,", "Normally,",
    "Nos,", "Not,", "Noted,", "Nothing,", "Novel,", "Now,", "Nowhere,", "Obtain,", "Obtained,",
    "Obviously,", "Of,", "Off,", "Often,", "Oh,", "Ok,", "Okay,", "Old,", "Om,", "Omitted,", "On,",
    "Once,", "One,", "Ones,", "Only,", "Onto,", "Or,", "Ord,", "Other,", "Others,", "Otherwise,",
    "Ought,", "Our,", "Ours,", "Ourselves,", "Out,", "Outside,", "Over,", "Overall,", "Ow,",
    "Owing,", "Own,", "Page,", "Pagecount,", "Pages,", "Part,", "Particular,", "Particularly,",
    "Past,", "Per,", "Perhaps,", "Placed,", "Please,", "Plus,", "Poorly,", "Possible,", "Possibly,",
    "Potentially,", "Predominantly,", "Present,", "Presumably,", "Previously,", "Primarily,",
    "Probably,", "Promptly,", "Proud,", "Provides,", "Put,", "Que,", "Quickly,", "Quite,", "Ran,",
    "Rather,", "Readily,", "Really,", "Reasonably,", "Recent,", "Recently,", "Ref,", "Refs,",
    "Regarding,", "Regardless,", "Regards,", "Related,", "Relatively,", "Research,",
    "Research-articl,", "Respectively,", "Resulted,", "Resulting,", "Results,", "Right,", "Run,",
    "Said,", "Same,", "Saw,", "Say,", "Saying,", "Says,", "Sec,", "Second,", "Secondly,",
    "Section,", "See,", "Seeing,", "Seem,", "Seemed,", "Seeming,", "Seems,", "Seen,", "Self,",
    "Selves,", "Sensible,", "Sent,", "Serious,", "Seriously,", "Seven,", "Several,", "Shall,",
    "Shan,", "Shan't,", "She,", "Shed,", "She'd,", "She'll,", "Shes,", "She's,", "Should,",
    "Shouldn,", "Shouldn't,", "Should've,", "Show,", "Showed,", "Shown,", "Showns,", "Shows,",
    "Side,", "Significant,", "Significantly,", "Similar,", "Similarly,", "Since,", "Sincere,",
    "Six,", "Sixty,", "Slightly,", "So,", "Some,", "Somebody,", "Somehow,", "Someone,", "Somethan,",
    "Something,", "Sometime,", "Sometimes,", "Somewhat,", "Somewhere,", "Soon,", "Sorry,",
    "Specifically,", "Specified,", "Specify,", "Specifying,", "Still,", "Stop,", "Strongly,",
    "Sub,", "Substantially,", "Successfully,", "Such,", "Sufficiently,", "Suggest,", "Sup,",
    "Sure,", "System,", "Take,", "Taken,", "Taking,", "Tell,", "Ten,", "Tends,", "Than,", "Thank,",
    "Thanks,", "Thanx,", "That,", "That'll,", "Thats,", "That's,", "That've,", "The,", "Their,",
    "Theirs,", "Them,", "Themselves,", "Then,", "Thence,", "There,", "Thereafter,", "Thereby,",
    "Thered,", "Therefore,", "Therein,", "There'll,", "Thereof,", "Therere,", "Theres,", "There's,",
    "Thereto,", "Thereupon,", "There've,", "These,", "They,", "Theyd,", "They'd,", "They'll,",
    "Theyre,", "They're,", "They've,", "Thickv,", "Thin,", "Think,", "Third,", "This,", "Thorough,",
    "Thoroughly,", "Those,", "Thou,", "Though,", "Thoughh,", "Thousand,", "Three,", "Throug,",
    "Through,", "Throughout,", "Thru,", "Thus,", "Til,", "To,", "Together,", "Too,", "Took,",
    "Top,", "Toward,", "Towards,", "Tried,", "Tries,", "Truly,", "Try,", "Trying,", "Twelve,",
    "Twenty,", "Twice,", "Two,", "U201d,", "Um,", "Under,", "Unfortunately,", "Unless,", "Unlike,",
    "Unlikely,", "Until,", "Unto,", "Up,", "Upon,", "Ups,", "Ur,", "Us,", "Use,", "Used,",
    "Useful,", "Usefully,", "Usefulness,", "Uses,", "Using,", "Usually,", "Value,", "Various,",
    "Very,", "Via,", "Viz,", "Vol,", "Vols,", "Volumtype,", "Want,", "Wants,", "Was,", "Wasn,",
    "Wasnt,", "Wasn't,", "Way,", "We,", "Wed,", "We'd,", "Welcome,", "Well,", "We'll,", "Well-b,",
    "Went,", "Were,", "We're,", "Weren,", "Werent,", "Weren't,", "We've,", "What,", "Whatever,",
    "What'll,", "Whats,", "What's,", "When,", "Whence,", "Whenever,", "When's,", "Where,",
    "Whereafter,", "Whereas,", "Whereby,", "Wherein,", "Wheres,", "Where's,", "Whereupon,",
    "Wherever,", "Whether,", "Which,", "While,", "Whim,", "Whither,", "Who,", "Whod,", "Whoever,",
    "Whole,", "Who'll,", "Whom,", "Whomever,", "Whos,", "Who's,", "Whose,", "Why,", "Why's,",
    "Widely,", "Will,", "Willing,", "Wish,", "With,", "Within,", "Without,", "Won,", "Wonder,",
    "Wont,", "Won't,", "Words,", "World,", "Would,", "Wouldn,", "Wouldnt,", "Wouldn't,", "Yes,",
    "Yet,", "You,", "Youd,", "You'd,", "You'll,", "Your,", "Youre,", "You're,", "Yours,",
    "Yourself,", "Yourselves,", "You've,", "Zero,", "Monday,", "Tuesday,", "Wednesday,",
    "Thursday,", "Friday,", "Saturday,", "Sunday,", "January,", "February,", "March,", "April,",
    "May,", "June,", "July,", "August,", "September,", "October,", "November,", "December,", "A,",
    "I,", "Able.", "About.", "Above.", "Abst.", "Accordance.", "According.", "Accordingly.",
    "Across.", "Act.", "Actually.", "Ad.", "Added.", "Adj.", "Affected.", "Affecting.", "Affects.",
    "After.", "Afterwards.", "Again.", "Against.", "Ah.", "Ain.", "Ain't.", "All.", "Allow.",
    "Allows.", "Almost.", "Alone.", "Along.", "Already.", "Also.", "Although.", "Always.", "Am.",
    "Among.", "Amongst.", "Amoungst.", "Amount.", "An.", "And.", "Announce.", "Another.", "Any.",
    "Anybody.", "Anyhow.", "Anymore.", "Anyone.", "Anything.", "Anyway.", "Anyways.", "Anywhere.",
    "Apart.", "Apparently.", "Appear.", "Appreciate.", "Appropriate.", "Approximately.", "Are.",
    "Aren.", "Arent.", "Aren't.", "Arise.", "Around.", "As.", "Aside.", "Ask.", "Asking.",
    "Associated.", "At.", "Auth.", "Available.", "Away.", "Awfully.", "Back.", "Be.", "Became.",
    "Because.", "Become.", "Becomes.", "Becoming.", "Been.", "Before.", "Beforehand.", "Begin.",
    "Beginning.", "Beginnings.", "Begins.", "Behind.", "Being.", "Believe.", "Below.", "Beside.",
    "Besides.", "Best.", "Better.", "Between.", "Beyond.", "Bill.", "Both.", "Bottom.", "Brief.",
    "Briefly.", "But.", "Call.", "Came.", "Can.", "Cannot.", "Cant.", "Can't.", "Cause.", "Causes.",
    "Certain.", "Certainly.", "Changes.", "Clearly.", "C'mon.", "Come.", "Comes.", "Concerning.",
    "Consequently.", "Consider.", "Considering.", "Contain.", "Containing.", "Contains.",
    "Corresponding.", "Could.", "Couldn.", "Couldnt.", "Couldn't.", "Course.", "Cry.", "Currently.",
    "Date.", "Definitely.", "Describe.", "Described.", "Despite.", "Detail.", "Did.", "Didn.",
    "Didn't.", "Different.", "Do.", "Does.", "Doesn.", "Doesn't.", "Doing.", "Don.", "Done.",
    "Don't.", "Down.", "Downwards.", "Due.", "During.", "Each.", "Effect.", "Eight.", "Eighty.",
    "Either.", "Eleven.", "Else.", "Elsewhere.", "Empty.", "End.", "Ending.", "Enough.",
    "Entirely.", "Especially.", "Et-al.", "Etc.", "Even.", "Ever.", "Every.", "Everybody.",
    "Everyone.", "Everything.", "Everywhere.", "Ex.", "Exactly.", "Example.", "Except.", "Far.",
    "Few.", "Fifteen.", "Fifth.", "Fify.", "Fill.", "Find.", "Fire.", "First.", "Five.", "Fix.",
    "Followed.", "Following.", "Follows.", "For.", "Former.", "Formerly.", "Forth.", "Forty.",
    "Found.", "Four.", "From.", "Front.", "Full.", "Further.", "Furthermore.", "Gave.", "Get.",
    "Gets.", "Getting.", "Give.", "Given.", "Gives.", "Giving.", "Go.", "Goes.", "Going.", "Gone.",
    "Got.", "Gotten.", "Greetings.", "Had.", "Hadn.", "Hadn't.", "Happens.", "Hardly.", "Has.",
    "Hasn.", "Hasnt.", "Hasn't.", "Have.", "Haven.", "Haven't.", "Having.", "He.", "Hed.", "He'd.",
    "He'll.", "Hello.", "Help.", "Hence.", "Her.", "Here.", "Hereafter.", "Hereby.", "Herein.",
    "Heres.", "Here's.", "Hereupon.", "Hers.", "Herself.", "Hes.", "He's.", "Hi.", "Hid.", "Him.",
    "Himself.", "His.", "Hither.", "Home.", "Hopefully.", "How.", "Howbeit.", "However.", "How's.",
    "Http.", "Hundred.", "Ibid.", "Id.", "I'd.", "If.", "Ignored.", "I'll.", "I'm.", "Immediate.",
    "Immediately.", "Importance.", "Important.", "Inasmuch.", "Inc.", "Indeed.", "Index.",
    "Indicate.", "Indicated.", "Indicates.", "Information.", "Inner.", "Insofar.", "Instead.",
    "Interest.", "Into.", "Invention.", "Inward.", "Is.", "Isn.", "Isn't.", "It.", "Itd.", "It'd.",
    "It'll.", "Its.", "It's.", "Itself.", "I've.", "Just.", "Keep.", "Keeps.", "Kept.", "Know.",
    "Known.", "Knows.", "Largely.", "Last.", "Lately.", "Later.", "Latter.", "Latterly.", "Least.",
    "Les.", "Less.", "Lest.", "Let.", "Lets.", "Let's.", "Like.", "Liked.", "Likely.", "Line.",
    "Little.", "Look.", "Looking.", "Looks.", "Ltd.", "Made.", "Mainly.", "Make.", "Makes.",
    "Many.", "May.", "Maybe.", "Me.", "Mean.", "Means.", "Meantime.", "Meanwhile.", "Merely.",
    "Might.", "Mightn.", "Mightn't.", "Mill.", "Million.", "Mine.", "Miss.", "More.", "Moreover.",
    "Most.", "Mostly.", "Move.", "Mr.", "Mrs.", "Ms.", "Mt.", "Much.", "Mug.", "Must.", "Mustn.",
    "Mustn't.", "My.", "Myself.", "Name.", "Namely.", "Nay.", "Near.", "Nearly.", "Necessarily.",
    "Necessary.", "Need.", "Needn.", "Needn't.", "Needs.", "Neither.", "Never.", "Nevertheless.",
    "New.", "Next.", "Nine.", "Ninety.", "No.", "Nobody.", "Non.", "None.", "Nonetheless.",
    "Noone.", "Nor.", "Normally.", "Nos.", "Not.", "Noted.", "Nothing.", "Novel.", "Now.",
    "Nowhere.", "Obtain.", "Obtained.", "Obviously.", "Of.", "Off.", "Often.", "Oh.", "Ok.",
    "Okay.", "Old.", "Om.", "Omitted.", "On.", "Once.", "One.", "Ones.", "Only.", "Onto.", "Or.",
    "Ord.", "Other.", "Others.", "Otherwise.", "Ought.", "Our.", "Ours.", "Ourselves.", "Out.",
    "Outside.", "Over.", "Overall.", "Ow.", "Owing.", "Own.", "Page.", "Pagecount.", "Pages.",
    "Part.", "Particular.", "Particularly.", "Past.", "Per.", "Perhaps.", "Placed.", "Please.",
    "Plus.", "Poorly.", "Possible.", "Possibly.", "Potentially.", "Predominantly.", "Present.",
    "Presumably.", "Previously.", "Primarily.", "Probably.", "Promptly.", "Proud.", "Provides.",
    "Put.", "Que.", "Quickly.", "Quite.", "Ran.", "Rather.", "Readily.", "Really.", "Reasonably.",
    "Recent.", "Recently.", "Ref.", "Refs.", "Regarding.", "Regardless.", "Regards.", "Related.",
    "Relatively.", "Research.", "Research-articl.", "Respectively.", "Resulted.", "Resulting.",
    "Results.", "Right.", "Run.", "Said.", "Same.", "Saw.", "Say.", "Saying.", "Says.", "Sec.",
    "Second.", "Secondly.", "Section.", "See.", "Seeing.", "Seem.", "Seemed.", "Seeming.", "Seems.",
    "Seen.", "Self.", "Selves.", "Sensible.", "Sent.", "Serious.", "Seriously.", "Seven.",
    "Several.", "Shall.", "Shan.", "Shan't.", "She.", "Shed.", "She'd.", "She'll.", "Shes.",
    "She's.", "Should.", "Shouldn.", "Shouldn't.", "Should've.", "Show.", "Showed.", "Shown.",
    "Showns.", "Shows.", "Side.", "Significant.", "Significantly.", "Similar.", "Similarly.",
    "Since.", "Sincere.", "Six.", "Sixty.", "Slightly.", "So.", "Some.", "Somebody.", "Somehow.",
    "Someone.", "Somethan.", "Something.", "Sometime.", "Sometimes.", "Somewhat.", "Somewhere.",
    "Soon.", "Sorry.", "Specifically.", "Specified.", "Specify.", "Specifying.", "Still.", "Stop.",
    "Strongly.", "Sub.", "Substantially.", "Successfully.", "Such.", "Sufficiently.", "Suggest.",
    "Sup.", "Sure.", "System.", "Take.", "Taken.", "Taking.", "Tell.", "Ten.", "Tends.", "Than.",
    "Thank.", "Thanks.", "Thanx.", "That.", "That'll.", "Thats.", "That's.", "That've.", "The.",
    "Their.", "Theirs.", "Them.", "Themselves.", "Then.", "Thence.", "There.", "Thereafter.",
    "Thereby.", "Thered.", "Therefore.", "Therein.", "There'll.", "Thereof.", "Therere.", "Theres.",
    "There's.", "Thereto.", "Thereupon.", "There've.", "These.", "They.", "Theyd.", "They'd.",
    "They'll.", "Theyre.", "They're.", "They've.", "Thickv.", "Thin.", "Think.", "Third.", "This.",
    "Thorough.", "Thoroughly.", "Those.", "Thou.", "Though.", "Thoughh.", "Thousand.", "Three.",
    "Throug.", "Through.", "Throughout.", "Thru.", "Thus.", "Til.", "To.", "Together.", "Too.",
    "Took.", "Top.", "Toward.", "Towards.", "Tried.", "Tries.", "Truly.", "Try.", "Trying.",
    "Twelve.", "Twenty.", "Twice.", "Two.", "U201d.", "Um.", "Under.", "Unfortunately.", "Unless.",
    "Unlike.", "Unlikely.", "Until.", "Unto.", "Up.", "Upon.", "Ups.", "Ur.", "Us.", "Use.",
    "Used.", "Useful.", "Usefully.", "Usefulness.", "Uses.", "Using.", "Usually.", "Value.",
    "Various.", "Very.", "Via.", "Viz.", "Vol.", "Vols.", "Volumtype.", "Want.", "Wants.", "Was.",
    "Wasn.", "Wasnt.", "Wasn't.", "Way.", "We.", "Wed.", "We'd.", "Welcome.", "Well.", "We'll.",
    "Well-b.", "Went.", "Were.", "We're.", "Weren.", "Werent.", "Weren't.", "We've.", "What.",
    "Whatever.", "What'll.", "Whats.", "What's.", "When.", "Whence.", "Whenever.", "When's.",
    "Where.", "Whereafter.", "Whereas.", "Whereby.", "Wherein.", "Wheres.", "Where's.",
    "Whereupon.", "Wherever.", "Whether.", "Which.", "While.", "Whim.", "Whither.", "Who.", "Whod.",
    "Whoever.", "Whole.", "Who'll.", "Whom.", "Whomever.", "Whos.", "Who's.", "Whose.", "Why.",
    "Why's.", "Widely.", "Will.", "Willing.", "Wish.", "With.", "Within.", "Without.", "Won.",
    "Wonder.", "Wont.", "Won't.", "Words.", "World.", "Would.", "Wouldn.", "Wouldnt.", "Wouldn't.",
    "Yes.", "Yet.", "You.", "Youd.", "You'd.", "You'll.", "Your.", "Youre.", "You're.", "Yours.",
    "Yourself.", "Yourselves.", "You've.", "Zero.", "Monday.", "Tuesday.", "Wednesday.",
    "Thursday.", "Friday.", "Saturday.", "Sunday.", "January.", "February.", "March.", "April.",
    "May.", "June.", "July.", "August.", "September.", "October.", "November.", "December.", "A.",
    "I.",
];
